INSERT INTO project.DeviceGroups (DeviceID, GroupName)
VALUES 
(1, 'Smart Home Group'),
(2, 'Smart Home Group'),
(3, 'Wearable Group'),
(4, 'Wearable Group'),
(5, 'Smart City Group'),
(6, 'Smart City Group'),
(7, 'IIoT Group'),
(8, 'IIoT Group'),
(9, 'Garage Group'),
(10, 'Garage Group'),
(11, 'Agricultural IoT Group'),
(12, 'Agricultural IoT Group'),
(13, 'Smart Retail Group'),
(14, 'Smart Retail Group'),
(15, 'Healthcare IoT Group'),
(16, 'Healthcare IoT Group'),
(17, 'Smart Grid Group'),
(18, 'Living Room Group'),
(19, 'Living Room Group'); 