INSERT INTO project.Devices (DeviceName, DeviceType, DeviceStatus)
VALUES 
('Nest Thermostat', 'Smart Home', 'Active'),
('Philips Hue', 'Smart Home', 'Inactive'),
('Fitbit', 'Wearable', 'Active'),
('Google Glass', 'Wearable', 'Inactive'),
('Traffic Control System', 'Smart City', 'Active'),
('Waste Management System', 'Smart City', 'Inactive'),
('Predictive Maintenance Device', 'IIoT', 'Active'),
('Asset Tracking Device', 'IIoT', 'Active'),
('Tesla Car', 'Connected Car', 'Active'),
('Apple CarPlay', 'Connected Car', 'Active'),
('Smart Irrigation System', 'Agricultural IoT', 'Active'),
('Crop Monitoring System', 'Agricultural IoT', 'Active'),
('IoT-enabled POS', 'Smart Retail', 'Active'),
('RFID Inventory Tracking Chip', 'Smart Retail', 'Inactive'),
('Remote Patient Monitoring Device', 'Healthcare IoT', 'Inactive'),
('Smart Bed', 'Healthcare IoT', 'Active'),
('Smart Meter', 'Smart Grid', 'Active'),
('Smart TV', 'Consumer Electronics', 'Active'),
('Drone', 'Consumer Electronics', 'Active');