INSERT INTO project.Users (UserName, UserEmail, UserPassword) VALUES
('John Doe', 'john.doe@example.com', 'Jd#9123'),
('Jane Smith', 'jane.smith@example.com', 'Js#8746'),
('Robert Johnson', 'robert.johnson@example.com', 'Rj#7635'),
('Michael Williams', 'michael.williams@example.com', 'Mw#6842'),
('Sarah Jones', 'sarah.jones@example.com', 'Sj#5931'),
('Jessica Brown', 'jessica.brown@example.com', 'Jb#5028'),
('Thomas Davis', 'thomas.davis@example.com', 'Td#4117'),
('Emily Miller', 'emily.miller@example.com', 'Em#3206'),
('Daniel Wilson', 'daniel.wilson@example.com', 'Dw#2395'),
('Emma Moore', 'emma.moore@example.com', 'Em#1584'),
('James Taylor', 'james.taylor@example.com', 'Jt#0773'),
('Sophia Anderson', 'sophia.anderson@example.com', 'Sa#9862'),
('William Thomas', 'william.thomas@example.com', 'Wt#8951'),
('Olivia Jackson', 'olivia.jackson@example.com', 'Oj#8040'),
('David White', 'david.white@example.com', 'Dw#7139'),
('Ava Harris', 'ava.harris@example.com', 'Ah#6238'),
('Joseph Martin', 'joseph.martin@example.com', 'Jm#5327');